env:
  global:
    - CC_TEST_REPORTER_ID=761b8572f93df2a58bc5485130ea11ca224af898e24a1fe6be351940ea732039
language: java
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
after_success:
  - bash <(curl -s https://codecov.io/bash)